spring:
  data:
    cassandra:
      contact-points: 218.38.18.111
      # local-datacenter: datacenter1
      port: 9042
      keyspace-name: test_hankook_6
      username: cassandra
      password: cassandra
      #schema-act: create_if_not_exists

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui-custom.html
#logging:
#  level:
#    root: DEBUG
